language: elixir
sudo: false
notifications:
  email: false

elixir:
  - 1.7

otp_release:
  - 21.1

addons:
  postgresql: "9.4"
services:
  - postgresql

cache:
  directories:
    - _build
    - deps

script:
  - make ci
after_success:
  - bash <(curl -s https://codecov.io/bash)
